
import entidades.Alumno;
import entidades.Materia;
import java.util.HashSet;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author crn70
 */
public class guiMain extends javax.swing.JFrame {
    public static HashSet<Alumno> listaAlumnos= new HashSet<>();
    public static HashSet<Materia> listaMateria= new HashSet<>();
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(guiMain.class.getName());

    /**
     * Creates new form guiMain
     */
    public guiMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuAlumno = new javax.swing.JMenu();
        MenuItemAlumno = new javax.swing.JMenuItem();
        jMenuMateria = new javax.swing.JMenu();
        jMenuItemMateria = new javax.swing.JMenuItem();
        jMenuRegistro = new javax.swing.JMenu();
        jMenuItemInscripcion = new javax.swing.JMenuItem();
        jMenuSalir = new javax.swing.JMenu();
        MenuItemSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 693, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 526, Short.MAX_VALUE)
        );

        jMenuAlumno.setText("Alumno");
        jMenuAlumno.addActionListener(this::jMenuAlumnoActionPerformed);

        MenuItemAlumno.setText("Agregar Alumnos");
        MenuItemAlumno.addActionListener(this::MenuItemAlumnoActionPerformed);
        jMenuAlumno.add(MenuItemAlumno);

        jMenuBar1.add(jMenuAlumno);

        jMenuMateria.setText("Materia");
        jMenuMateria.addActionListener(this::jMenuMateriaActionPerformed);

        jMenuItemMateria.setText("Formulario de Materias");
        jMenuItemMateria.addActionListener(this::jMenuItemMateriaActionPerformed);
        jMenuMateria.add(jMenuItemMateria);

        jMenuBar1.add(jMenuMateria);

        jMenuRegistro.setText("Registro");
        jMenuRegistro.addActionListener(this::jMenuRegistroActionPerformed);

        jMenuItemInscripcion.setText("Formulario de Inscripcion");
        jMenuItemInscripcion.addActionListener(this::jMenuItemInscripcionActionPerformed);
        jMenuRegistro.add(jMenuItemInscripcion);

        jMenuBar1.add(jMenuRegistro);

        jMenuSalir.setText("Salir");
        jMenuSalir.addActionListener(this::jMenuSalirActionPerformed);

        MenuItemSalir.setText("Salir");
        MenuItemSalir.addActionListener(this::MenuItemSalirActionPerformed);
        jMenuSalir.add(MenuItemSalir);

        jMenuBar1.add(jMenuSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(escritorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(escritorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuItemAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemAlumnoActionPerformed
      
        
         escritorio.removeAll();
       escritorio.repaint();
            guiAlumnos alumnos = new guiAlumnos();
        escritorio.add(alumnos);
        alumnos.setVisible(true);
        escritorio.moveToFront(alumnos);
        
        
        
    }//GEN-LAST:event_MenuItemAlumnoActionPerformed

    private void jMenuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSalirActionPerformed
        
    }//GEN-LAST:event_jMenuSalirActionPerformed

    private void MenuItemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemSalirActionPerformed


System.exit(0);


        // TODO add your handling code here:
    }//GEN-LAST:event_MenuItemSalirActionPerformed

    private void jMenuAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAlumnoActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jMenuAlumnoActionPerformed

    private void jMenuMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuMateriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuMateriaActionPerformed

    private void jMenuRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuRegistroActionPerformed
        // TODO add your handling code here:   
    }//GEN-LAST:event_jMenuRegistroActionPerformed

    private void jMenuItemMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemMateriaActionPerformed
        // TODO add your handling code here:
        
        
        
          escritorio.removeAll();
       escritorio.repaint();
            guiMateria materia = new guiMateria();
        escritorio.add(materia);
        materia.setVisible(true);
        escritorio.moveToFront(materia);
        
        
    }//GEN-LAST:event_jMenuItemMateriaActionPerformed

    private void jMenuItemInscripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemInscripcionActionPerformed
        // TODO add your handling code here:
        
         escritorio.removeAll();
       escritorio.repaint();
            guiInscripciones inscripciones = new guiInscripciones();
        escritorio.add(inscripciones);
        inscripciones.setVisible(true);
        escritorio.moveToFront(inscripciones);
        
        
        
    }//GEN-LAST:event_jMenuItemInscripcionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new guiMain().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenuItemAlumno;
    private javax.swing.JMenuItem MenuItemSalir;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenu jMenuAlumno;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemInscripcion;
    private javax.swing.JMenuItem jMenuItemMateria;
    private javax.swing.JMenu jMenuMateria;
    private javax.swing.JMenu jMenuRegistro;
    private javax.swing.JMenu jMenuSalir;
    // End of variables declaration//GEN-END:variables
}
